import { Translations } from '../contexts/LanguageContext';

const en: Translations = {
  // Common
  common: {
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    add: 'Add',
    loading: 'Loading...',
    error: 'Error',
    success: 'Success',
    confirm: 'Confirm',
    back: 'Back',
    next: 'Next',
    search: 'Search',
    filter: 'Filter',
    actions: 'Actions',
    status: 'Status',
    name: 'Name',
    description: 'Description',
    price: 'Price',
    email: 'Email',
    phone: 'Phone',
    address: 'Address',
  },
  
  // Navigation
  nav: {
    dashboard: 'Dashboard',
    orders: 'Orders',
    menu: 'Menu',
    tables: 'Tables',
    staff: 'Staff',
    settings: 'Settings',
    analytics: 'Analytics',
    logout: 'Logout',
    switchRestaurant: 'Switch Restaurant',
    signOut: 'Sign Out',
    selectRestaurant: 'Select restaurant',
    language: 'Language',
    languageSettings: 'Language Settings',
  },
  
  // Dashboard
  dashboard: {
    title: 'Dashboard',
    welcomeBack: 'Welcome back! Here\'s what\'s happening today.',
    todayRevenue: "Today's Revenue",
    activeOrders: 'Active Orders',
    ordersToday: 'Orders Today',
    avgOrderValue: 'Avg Order Value',
    recentOrders: 'Recent Orders',
    todayPerformance: "Today's Performance",
    revenueToday: 'Revenue Today',
    systemStatus: 'System Status',
    kitchenDisplay: 'Kitchen Display',
    paymentSystem: 'Payment System',
    qrOrdering: 'QR Ordering',
    quickActions: 'Quick Actions',
    viewMenu: 'View Menu',
    manageTables: 'Manage Tables',
    updateTableLayout: 'Update table layout',
    viewAllOrders: 'View all',
    noRecentOrders: 'No recent orders',
    items: 'items',
    viewOrders: 'View Orders',
    manageMenu: 'Manage Menu',
    addNewItems: 'Add new items to your menu',
    addMenuItem: 'Add Menu Item',
    createNewDish: 'Create a new dish',
  },
  
  // Orders
  orders: {
    title: 'Orders',
    liveOrders: 'Live Orders',
    manageActiveOrders: 'Manage active restaurant orders',
    newOrder: 'New Order',
    pending: 'Pending',
    confirmed: 'Confirmed',
    preparing: 'Preparing',
    ready: 'Ready',
    delivered: 'Delivered',
    completed: 'Completed',
    cancelled: 'Cancelled',
    table: 'Table',
    orderNumber: 'Order',
    total: 'Total',
    time: 'Time',
    loadingOrders: 'Loading orders...',
    error: 'Error',
    tryAgain: 'Try Again',
    live: 'Live',
    offline: 'Offline',
    creating: 'Creating...',
    testOrder: 'Test Order',
    refresh: 'Refresh',
    noActiveOrders: 'No active orders',
    newOrdersWillAppear: 'New orders will appear here when customers place them.',
    items: 'items',
    markAs: 'Mark as',
    note: 'Note',
  },
  
  // Tables
  tables: {
    title: 'Tables',
    addTable: 'Add Table',
    tableNumber: 'Table Number',
    capacity: 'Capacity',
    qrCode: 'QR Code',
    downloadQr: 'Download QR',
    viewFullSize: 'View Full Size',
    available: 'Available',
    occupied: 'Occupied',
    reserved: 'Reserved',
    maintenance: 'Maintenance',
    qrCodeNotAvailable: 'QR code not available',
    qrCodesGenerated: 'QR codes are generated automatically when tables are created',
    manageTablesDescription: 'Manage restaurant tables and real-time status',
    live: 'Live',
    offline: 'Offline',
    refresh: 'Refresh',
    total: 'Total',
    outOfOrder: 'Out of Order',
    searchTables: 'Search tables...',
    allStatuses: 'All Statuses',
    noTablesFound: 'No tables found',
    createFirstTable: 'Create your first table to get started.',
    table: 'Table',
    seats: 'seats',
    code: 'Code',
    viewQr: 'View QR',
    qrCodeFor: 'QR Code - Table',
    permanentQrCode: 'Permanent QR Code',
    permanentQrDescription: 'This QR code is permanent and safe for printing on physical materials. It will never change unless manually regenerated by an admin.',
    customerUrl: 'Customer URL',
    customerUrlDescription: 'Customers will be redirected to this URL when they scan the QR code',
  },
  
  // Menu
  menu: {
    // Page titles and headers
    title: 'Menu',
    menuManagement: 'Menu Management',
    loading: 'Loading menu...',
    retry: 'Retry',
    pleaseSelectRestaurant: 'Please select a restaurant to manage menu.',
    
    // Actions
    addMenuItem: 'Add Menu Item',
    addCategory: 'Add Category',
    edit: 'Edit',
    hide: 'Hide',
    show: 'Show',
    
    // Categories
    category: 'Category',
    categories: 'Categories',
    filterByCategory: 'Filter by Category',
    allItems: 'All Items',
    createNewCategory: 'Create New Category',
    
    // Item status
    available: 'Available',
    unavailable: 'Unavailable',
    hidden: 'Hidden',
    notVisibleToCustomers: 'Not visible to customers',
    
    // Visibility toggle
    showHidden: 'Show Hidden',
    hideUnavailable: 'Hide Unavailable',
    
    // Empty states
    noMenuItemsFound: 'No menu items found',
    startByAddingFirstItem: 'Start by adding your first menu item.',
    
    // Modal titles
    addNewMenuItem: 'Add New Menu Item',
    editMenuItem: 'Edit Menu Item',
    
    // Error states
    error: 'Error',
  },
  
  // Restaurant
  restaurant: {
    selectRestaurant: 'Select Restaurant',
    addRestaurant: 'Add Restaurant',
    restaurantName: 'Restaurant Name',
    logoUrl: 'Logo URL',
    welcome: 'Welcome',
    chooseRestaurant: 'choose a restaurant to manage',
    noRestaurantsFound: 'No restaurants found',
    noRestaurantsAvailable: 'No restaurants available in the system',
    createRestaurant: 'Create Restaurant',
    creating: 'Creating...',
    requiredFields: 'Required fields',
    tryAgain: 'Try again',
  },
  
  // Auth
  auth: {
    login: 'Login',
    logout: 'Logout',
    email: 'Email',
    password: 'Password',
    forgotPassword: 'Forgot Password',
    rememberMe: 'Remember Me',
    signIn: 'Sign In',
  },
  
  // Validation & Errors
  validation: {
    required: 'Required',
    invalidEmail: 'Invalid email',
    passwordTooShort: 'Password too short',
    phoneInvalid: 'Invalid phone number',
    urlInvalid: 'Invalid URL',
    networkError: 'Network error',
    apiNotRunning: 'make sure API is running',
  },
  
  // Time & Dates
  time: {
    justNow: 'just now',
    minutesAgo: 'minutes ago',
    hoursAgo: 'hours ago',
    daysAgo: 'days ago',
    weeksAgo: 'weeks ago',
    monthsAgo: 'months ago',
  },
};

export default en;